export const views = Object.freeze({
    MAIN_AREA: 'MAIN_AREA',
    HEADER_AREA: 'HEADER_AREA',
    MAIN_SEARCH_VIEW: 'MAIN_SEARCH_VIEW',
    MAIN_FORECAST_VIEW: 'MAIN_FORECAST_VIEW',
    MAIN_RECENT_VIEW: 'MAIN_RECENT_VIEW',
    HEADER_DEFAULT_VIEW: 'HEADER_DEFAULT_VIEW',
    HEADER_SEARCH_VIEW: 'HEADER_SEARCH_VIEW'
});